version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: elite_defense_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: elite_defense_academy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql

volumes:
  pgdata:
